# Generated by Django 5.2.8 on 2025-11-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('estimated_hours', models.IntegerField(default=1)),
                ('importance', models.IntegerField(default=5)),
                ('dependencies', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
